version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dodo
      - JWT_SECRET=your-super-secret-key-change-this-in-production
      - RUST_LOG=debug
    depends_on:
      - db
    networks:
      - dodo-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dodo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dodo-network

volumes:
  postgres_data:

networks:
  dodo-network:
    driver: bridge 